name: Publish coverage metrics

on:
  workflow_call:
    # Map the workflow outputs to job outputs
    inputs:
      triggering-sha:
        required: true
        type: string

env:
  # GHA SETTINGS
  USE_COMPOSER_CACHE: '1'
  USE_PHP_EXTENSION_CACHE: '1'
  # PHP SETTINGS
  PHP_EXTENSIONS: ctype, iconv, json, curl, gd, intl, opcache, openssl, mbstring, mysql, pdo_sqlite
  PHP_EXTENSIONS_CACHE_KEY: cache-php-extensions-v1
  # ARTIFACTS SETTINGS
  ARTIFATC_NAME_FOR_UNIT_TESTS_COVERAGE: 'Unit-test-coverage-reports-on-SHA'
  UNIT_TEST_CLOVER_FILENAME: 'coverage-unit-test-clover.xml'
  ARTIFATC_NAME_FOR_UNIT_TESTS_DOCUMENTATION_REPORT: 'Unit-test-docs-report-on-SHA'
  UNIT_TEST_DOC_FILENAME: 'doc-unit-test.txt'


jobs:
  publish-unit-test-report:
    name: Publish unit test report
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on SHA-${{ inputs.triggering-sha }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.triggering-sha }}

      - name: Get Coverage artifact name
        id: coverage-artifact-name
        run: echo "name=$ARTIFATC_NAME_FOR_UNIT_TESTS_COVERAGE-$GITHUB_SHA" >> $GITHUB_OUTPUT

      - name: Download unit test coverage artifact
        id: download-unit-test-coverage-artifact
        run: |
          ls -al
          gh run download -n ${{ steps.coverage-artifact-name.outputs.name }}
          ls -al
        #env:
          #GITHUB_TOKEN: ${{ secrets.GH_API_ARTIFACT_ACTION }}

#      - name: Upload coverage results to Codecov
#        if: ${{ (steps.download-unit-test-coverage-artifact.outcome == 'success')}}
#        uses: codecov/codecov-action@v1
#        with:
#          files: ${{ env.COVERAGE_CLOVER_UNIT_FILENAME }}
#          name: Unit test
#          flags: unit-test
#          fail_ci_if_error: false
#        continue-on-error: true
